lang: en-GB
timezone:  Europe/London
repo: https://github.com/jmshtr/jmshtr.github.io # site repo
permalink: /:year:month:day/:title
version: "1.2.1"

# URL settings
url: "https://jmshtr.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site is not in the root of the host
permalink: pretty

author:
  name: jmshtr
  description: personal website

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  style: :compressed
  sass_dir: _sass

plugins:
  - jekyll-last-modified-at