permalink: /:year:month:day/:title
url: https://jsmhtr.github.io
lang: en
baseurl: # blank on purpose
repo: https://github.com/jmshtr/jmshtr.github.io

author:
  name: jmshtr
  description: personal website
  google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true